name: ci/cd
on:
    push:
        branches: "production"

# commit message with format:
#  repo path: branch
# e.g: vdx-vn/cuu-long:dev

# #1:
# prepare venv - b

jobs:
    pylint-test:
        runs-on: ubuntu-latest
        environment: vdx-vn/cuu-long
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: check variables
              run: |
                  echo ${S1}
                  echo ${V1}
