name: ci/cd
on:
    push:
        branches: "production"

# commit message with format:
#  repo path: branch
# e.g: vdx-vn/cuu-long:dev
# #1:.
# prepare venv - b

jobs:
    pylint-test:
        runs-on: ubuntu-latest
        environment: ${{github.event.head_commit.message}}
        steps:
            - name: Checkout private repo
              uses: actions/checkout@v4
              # fixme: move ACCESS_TOKEN to global config (instead of environment)
              with:
                  repository: ${{ vars.PATH }}
                  token: ${{ secrets.ACCESS_TOKEN }}
                  path: ${{ github.workspace }}/private_repo_source
                  ref: ${{ vars.BRANCH }}
                  fetch-depth: 1
            - name: test
              run: |
                  ls ${{github.workspace}}/private_repo_source
