name: ci/cd
on:
    push:
        branches: "production"

# commit message with format:
#  repo path: branch
# e.g: vdx-vn/cuu-long:dev
# #1:
# prepare venv - b

jobs:
    pylint-test:
        runs-on: ubuntu-latest
        environment: vdx-vn/cuu-long
        env:
            v1: ${{vars.V1}}
            s1: ${{secrets.S1}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: check variables
              run: |
                  echo ${v1}
                  echo ${s1}
